package com.logistics.platform.app.user.entity;

public enum PermissionType {
    USER_READ, USER_WRITE,
    SHIPMENT_READ, SHIPMENT_CREATE, SHIPMENT_UPDATE, SHIPMENT_CANCEL,
    TRACKING_READ, TRACKING_WRITE,
    PARTNER_READ, PARTNER_WRITE,
    WAREHOUSE_READ, WAREHOUSE_WRITE,
    PRICING_READ, PRICING_WRITE,
    AUDIT_READ
}
